name = "codecrafters_shell"
version = "1.0.0"

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
input = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
